### ISSUE TITLE
Sublime Merge does not remember window location when closed

### ISSUE THREAD

**Issue by michaelalandawson** [sublimehq/sublime_merge#1050]
**Version info**

 - OS: Windows 10
 - Build: 2042

**Description**

Sublime Merge does not remember the position of the window when it is closed and reopened.  The top-left corner of the window returns to top-left area of the desktop.

Upgraded Sublime Merge from the most-recent released version to build 2042.  I installed 2042 over the existing installation.  I did not clear out or remove any session-related files.  When I ran 2042 the first time, it opened the tabs for all previously-open repositories, as I would expect.  So, I assume it found existing session information.

**Steps to reproduce**

1. Open Sublime Merge
2. Move the window
3. Close Sublime Merge
4. Reopen Sublime Merge
5. Note that the position of the window is reset to the original location near the top-left corner of the desktop
6. Repeat as needed

**Comment by bakerkretzmar** [comment]
Duplicate of #396.

**Comment by michaelalandawson** [comment]
#396 is a related, but different issue.  I don't have an issue with Merge remembering the *size* of the window.  My issue is remembering the *position* of the window.

**Comment by dpjohnst** [comment]
Hi @michaelalandawson,

Thanks for reporting this issue - unfortunately I've been unable to reproduce the issue.

Could you confirm the following:

* Are you using a portable version of Sublime Merge?
* Are you starting Sublime Merge via the command line, and if so, how?

Kind regards,
\- Dylan

**Comment by Devenec** [comment]
Hi @dpjohnst,

I'm having the same issue on Windows 10 build 1909.

The issue occurs when starting Sublime Merge:
- Directly from the exe
- From shortcut (without command line arguments)
- From command line, by executing `.\sublime_merge.exe`

Sublime Merge used to remember the window position and size correctly (secondary display, fullscreen), but at some point it didn't anymore. I don't remember the version the issue started with. Now when I run it, the window is placed at the primary display, about half the size of the screen.

Best regards,
Eetu

**Comment by dpjohnst** [comment]
Hi all,

Thanks for reporting this issue.

This issue occurs when the selected tab is not the first tab in the list of tabs.
This will be resolved in the next build of Sublime Merge.

Cheers,
\- Dylan

**Comment by dpjohnst** [comment]
Hi all,

This has been resolved in the newly released Sublime Merge Build 2045.
Please reach out if you're still seeing this issue.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi all,

Just following up that the fix was released to the stable channel (Sublime Merge Build 2047)

Cheers,
\- Dylan

**Comment by Devenec** [comment]
Hi @dpjohnst,

the issue was indeed solved when the selected tab is not the first tab, but it still exists if the first tab is selected, or there are no tabs (only one repo open). I'm running dev channel build 2046.

Best,
Eetu

**Comment by highend** [comment]
Will this ever be fixed?

E.g. download the 64-bit portable version start it, don't open a repo. Move the window. It will never save its window position^^
