### ISSUE TITLE
incorrect "Remotes" count when doing subtree merges

### ISSUE THREAD

**Issue by braver** [sublimehq/sublime_merge#111]
**Version info**

 - OS: macOS 10.14
 - Build: 1069

**Description**

I'm merging a couple of repositories into one using subtree merging according to this guide: https://stackoverflow.com/questions/1683531/how-to-import-existing-git-repository-into-another/8396318#8396318. Some remotes show up in the list twice, the count shows 4 remotes whereas the list shows 6. 

<img width="202" alt="screen shot 2018-10-12 at 12 21 42" src="https://user-images.githubusercontent.com/2543659/46864269-20d37280-ce1a-11e8-95b0-41429e2c65e4.png">

**Debug info**

```
=== App Version Information ===
Build: 1069

=== Git Version Information ===
Using Git: git (system)
git version 2.17.1 (Apple Git-112)
PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

=== Browse Page Information ===
HEAD: ada30b04bd19b6650ef1978c18b73e437ca2738b
Is in merge: 0
Is in cherry_pick: 0
Is in rebase: 0
Is in revert: 0

=== Git Status Information ===

=== Our Status Information ===

=== Git Config Information ===
branch.cxx.merge=refs/heads/master
branch.cxx.remote=alan-2-cxx
branch.master.merge=refs/heads/master
branch.master.remote=origin
branch.monorepo.merge=refs/heads/monorepo
branch.monorepo.remote=origin
core.bare=false
core.editor=nano
core.excludesfile=~/.gitignore
core.filemode=true
core.ignorecase=true
core.logallrefupdates=true
core.precomposeunicode=true
core.repositoryformatversion=0
credential.helper=osxkeychain
remote.alan-2-cxx.fetch=+refs/heads/*:refs/remotes/alan-2-cxx/*
remote.alan-2-cxx.url=git@gitlab.m-industries.com:alan/alan-2-cxx.git
remote.alan-core.fetch=+refs/heads/*:refs/remotes/alan-core/*
remote.alan-core.url=git@gitlab.m-industries.com:alan/alan-core.git
remote.alan-implementation-2-cxx.fetch=+refs/heads/*:refs/remotes/alan-implementation-2-cxx/*
remote.alan-implementation-2-cxx.url=git@gitlab.m-industries.com:alan/alan-implementation-2-cxx.git
remote.alan-implementation.fetch=+refs/heads/*:refs/remotes/alan-implementation/*
remote.alan-implementation.url=git@gitlab.m-industries.com:alan/alan-implementation.git
remote.alan-to-text-transformation.fetch=+refs/heads/*:refs/remotes/alan-to-text-transformation/*
remote.alan-to-text-transformation.url=git@gitlab.m-industries.com:alan/alan-to-text-transformation.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=git@gitlab.m-industries.com:alan/alan.git
submodule.src/lib/c-toolbox.active=true
submodule.src/lib/c-toolbox.url=git@gitlab.m-industries.com:cxx-toolbox/c-toolbox.git
submodule.src/lib/cxx-toolbox.active=true
submodule.src/lib/cxx-toolbox.url=git@gitlab.m-industries.com:cxx-toolbox/cxx_toolbox.git
submodule.src/lib/package-api.active=true
submodule.src/lib/package-api.url=git@gitlab.m-industries.com:cxx-toolbox/cxx_api_package.git
user.email=koen.lageveen@me.com
user.name=Koen Lageveen

=== Our Config Information ===
Git Config Path Information
Using config path: /etc/gitconfig
Using config path: /Users/koenlageveen/.config/git/config
Using config path: /Users/koenlageveen/.gitconfig
Using config path: /Users/koenlageveen/Dev/alans/alan/.git/config

Our config output is different to the Git config output
branch.cxx.merge=refs/heads/master
branch.cxx.remote=alan-2-cxx
branch.master.merge=refs/heads/master
branch.master.remote=origin
branch.monorepo.merge=refs/heads/monorepo
branch.monorepo.remote=origin
core.bare=false
core.editor=nano
core.excludesfile=~/.gitignore
core.filemode=true
core.ignorecase=true
core.logallrefupdates=true
core.precomposeunicode=true
core.repositoryformatversion=0
remote.alan-2-cxx.fetch=+refs/heads/*:refs/remotes/alan-2-cxx/*
remote.alan-2-cxx.url=git@gitlab.m-industries.com:alan/alan-2-cxx.git
remote.alan-core.fetch=+refs/heads/*:refs/remotes/alan-core/*
remote.alan-core.url=git@gitlab.m-industries.com:alan/alan-core.git
remote.alan-implementation-2-cxx.fetch=+refs/heads/*:refs/remotes/alan-implementation-2-cxx/*
remote.alan-implementation-2-cxx.url=git@gitlab.m-industries.com:alan/alan-implementation-2-cxx.git
remote.alan-implementation.fetch=+refs/heads/*:refs/remotes/alan-implementation/*
remote.alan-implementation.url=git@gitlab.m-industries.com:alan/alan-implementation.git
remote.alan-to-text-transformation.fetch=+refs/heads/*:refs/remotes/alan-to-text-transformation/*
remote.alan-to-text-transformation.url=git@gitlab.m-industries.com:alan/alan-to-text-transformation.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=git@gitlab.m-industries.com:alan/alan.git
submodule.src/lib/c-toolbox.active=true
submodule.src/lib/c-toolbox.url=git@gitlab.m-industries.com:cxx-toolbox/c-toolbox.git
submodule.src/lib/cxx-toolbox.active=true
submodule.src/lib/cxx-toolbox.url=git@gitlab.m-industries.com:cxx-toolbox/cxx_toolbox.git
submodule.src/lib/package-api.active=true
submodule.src/lib/package-api.url=git@gitlab.m-industries.com:cxx-toolbox/cxx_api_package.git
user.email=koen.lageveen@me.com
user.name=Koen Lageveen

=== Git Attributes Information ===
git check_attr --all output

=== Our Modified Files Newline Normalisation and EOL Information ===
```

**Comment by jskinner** [comment]
This should be fixed in dev build 1071 - please let me know if you see it again.

**Comment by braver** [comment]
@jskinner I'm still seeing this problem using 1072. 

<img width="201" alt="screen shot 2018-10-13 at 14 42 14" src="https://user-images.githubusercontent.com/2543659/46905581-3b7b1980-cef6-11e8-842d-f91b781f5fb0.png">

**Comment by jskinner** [comment]
Thanks for the update, I think this should be actually fixed in the next build.
