### ISSUE TITLE
Git log links no longer clickable

### ISSUE THREAD

**Issue by matthewd-canva** [sublimehq/sublime_merge#1708]
**Version info**

 - OS: macOS 13.1
 - Build: 2083

**Description**

Prior to update the URLs in the git log were clickable. Now they are not.

**Steps to reproduce**

1. Open repository on github
2. Create a branch
3. Commit something
4. Push branch
5. Server responds with "Create a pull request... https://github.com/..."

**Expected behavior**

The URL is clickable.

**Screenshots**

![image](https://user-images.githubusercontent.com/59851522/217120108-b4e3ccd4-dbab-40c5-8719-696e2f9c096a.png)

URL in red should be clickable.

**Comment by dpjohnst** [comment]
G'day @matthewd-canva,

Thanks for reaching out and apologies for the delay in getting back to you.

I don't believe these links have been clickable via the left mouse button. 
You can open these links by opening the context menu and selecting `Open URL...`

Let me know if this doesn't work, and I can definitely investigate further.

Cheers,
\- Dylan from Sublime HQ

**Comment by matthewd-canva** [comment]
> I don't believe these links have been clickable via the left mouse button.

Incorrect. They were previously underlined and clickable with left mouse button.

If you can install the previous version you can confirm this.

**Comment by matthewd-canva** [comment]
I believe I simply had to hold CMD and I could double-left-click on the link to open it, avoiding right-click and moving mouse.

**Comment by dpjohnst** [comment]
Hi @matthewd-canva,

Thanks for the clarification - I have noted that the syntax highlighting has broken for the URLs and will be investigating this further.

Regarding opening the URL with CMD/Ctrl + left click, we haven't supported this by default. Perhaps you added a custom mouse-mapping to Sublime Merge?

Could you additionally confirm if you have a custom mouse mapping for Sublime Merge?
1. Open Sublime Merge
2. Via the application menu, select `Preferences > Browse Packages...`
3. Navigate to the `User` directory
4. Look for any files with the extension `.sublime-mousemap`

If you find any, could you share the contents of these files?

Kind regards,
\- Dylan from Sublime HQ

**Comment by matthewd-canva** [comment]
> Regarding opening the URL with CMD/Ctrl + left click, we haven't supported this by default. Perhaps you added a custom mouse-mapping to Sublime Merge?

I can confirm that I have never had any custom mouse-mappings, nor do I have one active now.

**Comment by dpjohnst** [comment]
G'day @matthewd-canva,

Thank you for confirming this!

We've identified the cause of the syntax highlighting issue, which will be resolved in the next build. I'll keep you updated here.

Regarding opening the URLs, we only support opening them via the context menu currently.
There is an open request to allow left-click by default which you can upvote/share your thoughts to here: https://github.com/sublimehq/sublime_merge/issues/989

Lastly, thanks for using Sublime Merge (and great to see someone from Canva using our tools - I have a close personal connection to Canva!).

Cheers,
\- Dylan from Sublime HQ

**Comment by dpjohnst** [comment]
G'day @matthewd-canva, just a quick update: 

We've fixed the syntax highlighting issue affecting the links in the Git output panel in Sublime Merge 2085, and the fix will also be included in the next stable build.

Cheers,
\- Dylan from Sublime HQ

**Comment by matthewd-canva** [comment]
Hi, the update has rolled out now. It now has syntax highlighting again, but the link is still not cmd+clickable:

![image](https://github.com/sublimehq/sublime_merge/assets/59851522/9102cd3a-5b4c-4f1f-bcae-4268d103cd13)

Previously I was able to cmd+click (or double click, I can't remember it's been so long) but now it just acts like text.
