### ISSUE TITLE
2115 - files showing as deleted when they exist

### ISSUE THREAD

**Issue by oconnor0** [sublimehq/sublime_merge#2111]
**Version info**

 - OS: Windows 10
 - Build: 2115

**Description**

After updating from 2111 to 2115, a whole bunch of .svg files in one directory showed as deleted. `git status` showed no changes and Ctrl+Enter on the file opened that file in Sublime Text. Nothing I tried seemed to change Sublime Merge's view here. (checkout, reset, stash, etc.)

I tried to see if there was a case issue, but it looked like at least some of the "deleted" files had the exact same case as the actual file.

**Steps to reproduce**

1. Open Sublime Merge 2111 with repo open.
2. Update to 2115.
3. See misreported files.

**Expected behavior**

Sublime Merge not to report the files as deleted.

**Comment by dpjohnst** [comment]
Hi @oconnor0,

Thanks for reporting this! I've just fixed this internally and the fix will be in the next build.

As a temporary workaround you can revert to build 2111 (see the _Show Downloads_ link below the build here https://www.sublimemerge.com/dev)

Cheers,
Dylan

**Comment by dpjohnst** [comment]
Hi @oconnor0,

We've just released Sublime Merge Build 2117 which resolves this.

Kind regards,
Dylan from Sublime HQ

**Comment by oconnor0** [comment]
2117 doesn't look like it fixes this for me. I get the same list of misreports as before. Sorry I haven't been able to provide more information on how/where this is happening.

**Comment by dpjohnst** [comment]
Hi @oconnor0,

Are you able to share your Sublime Merge debug information on the repository in question when you have a spare moment?
This would help me a lot in tracking down what's going on.

I've attached the steps below:

**Debug Information**
The Sublime Merge debug information can be used to narrow down the cause of an issue.
It can be collected with the following steps:
1. Open Sublime Merge
2. Open the repository where the bug occurs
3. Navigate to `Help > Debug Information` via the application menu
4. Before sharing, _please redact any information that's sensitive_ such as file paths, git user information, remote URLs etc.

Cheers,
Dylan from Sublime HQ

**Comment by oconnor0** [comment]
The list of "deleted" files is longer and the path is slightly different, but contains no spaces, so seemed OK to rewrite for this bug report.

```
=== App Version Information ===
Build: 2117

=== Git Version Information ===
Using Git: C:\Program Files\Sublime Merge\Git\cmd\git.exe (bundled)
git version 2.50.1.windows.1
PATH: C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Program Files\Microsoft\Web Platform Installer\;C:\ProgramData\chocolatey\bin;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\PuTTY\;C:\Program Files (x86)\cloudflared\;C:\Program Files\PowerShell\7\;C:\Program Files\dotnet\;C:\Program Files\LINQPad9;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\170\Tools\Binn\;C:\Program Files\Docker\Docker\resources\bin;C:\Users\oconnor0\go\bin

=== Browse Page Information ===
HEAD: c89c23f12afd53199a1daf5c2fc18abb16dcf3a6
Is in merge: 0
Is in cherry_pick: 0
Is in rebase: 0
Is in revert: 0

=== Git Status Information ===
?? a.json


=== Our Status Information ===
 D icons/file.svg
?? a.json

=== Git Config Information ===
alias.br=branch
alias.ci=commit
alias.cim=commit -m
alias.co=checkout
alias.last=log -1 HEAD
alias.st=status
alias.unstage=reset HEAD --
branch.autosetuprebase=always
branch.master.merge=refs/heads/master
branch.master.rebase=true
branch.master.remote=origin
color.interactive=true
color.ui=auto
core.autocrlf=false
core.bare=false
core.filemode=false
core.ignorecase=true
core.logallrefupdates=true
core.repositoryformatversion=0
core.symlinks=false
credential.helper=manager
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.smudge=git-lfs smudge -- %f
help.format=html
include.path=C:/Program Files/Git/etc/gitconfig
init.defaultbranch=master
pack.packsizelimit=2g
pull.rebase=true
rebase.autosquash=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=...
user.email=...
user.name=...

=== Our Config Information ===
Git Config Path Information
Using config path: /C/ProgramData/Git/config
Using config path: /C/Program Files/Sublime Merge/Git/etc/gitconfig
Using config path: /C/Users/oconnor0/.config/git/config
Using config path: /C/Users/oconnor0/.gitconfig
Using config path: /C/src/.git/config

Our config output is identical to the Git config output

=== Git Attributes Information ===
git check_attr --all output
a.json
icons/file.svg

=== Our Modified Files Newline Normalisation and EOL Information ===
icons/file.svg: unspecified - native

=== Our Modified Files Flag Information ===
Ignoring symlinks: 1
icons/file.svg: Working - Normal File : Index - Normal File

=== Staged Files Information ===

=== Repository Statistics ===
Commit Count: 43942
Untracked Files Count: 27
Modified Files Count: 43
Staged Files Count: 0
Submodule Count: 0
Loose Objects Count: 2010
Packfile Count: 48
```

**Comment by dpjohnst** [comment]
Hi @oconnor0,

Thanks for the additional debug information. I believe I've narrowed down the issue.

Could you confirm if:
* The repository is on a network drive, or on WSL
* There are any files in the `icons/` folder with the exact same name but different case (e.g. upper case, lower case, or mix)

Kind regards,
Dylan from Sublime HQ

**Comment by oconnor0** [comment]
No, it's not on a network drive or WSL.

Yes, there is an `icons/file.svg` and an `icons/File.svg` in the Git repo. Only one of those is available after checkout on Windows, I see.

**Comment by dpjohnst** [comment]
G'day @oconnor0,

We've just released Sublime Merge Build 2119 (Development Build), which should resolve this issue.

Could you confirm whether this has resolved the issue on your end?

Many thanks,
Dylan from Sublime HQ

**Comment by oconnor0** [comment]
2119 does not appear to resolve this issue for me. I don't know if the list of "deleted files" is different than it was before or not, but it looks similar.

**Comment by dpjohnst** [comment]
Hi @oconnor0,

We've just released Sublime Merge Build 2120. Could you confirm if this resolves the issue on your end?

Many thanks,
Dylan from Sublime HQ

**Comment by oconnor0** [comment]
Yes, that does it. Thanks for tracking this down.

**Comment by dpjohnst** [comment]
Glad it's resolved! Thank you for your patience in getting this investigated.
