### ISSUE TITLE
Wrong color on branch names

### ISSUE THREAD

**Issue by Herteby** [sublimehq/sublime_merge#221]
**Version info**

 - OS: CentOS Linux 7.5
 - Build: 1079

**Description**

In the branch graph, the current checked out branch is blue, and another branch is purple.
But when looking at the name tags to the right, the current branch is purple, and the other branch is blue.

**Expected behavior**

The name tags of the branches should have the same color as the branch in the graph.

**Screenshots**

![image](https://user-images.githubusercontent.com/6474685/48004662-ebb4fa00-e111-11e8-95cd-43bbc6133e05.png)

**Comment by MageFroh** [comment]
I've been wondering why it was hard to understand the commit tree in Sublime Merge (compared to other tools), and it feels like this is the one.

I tend to rely on colors a lot to organise things, and it is very confusing to have the same color for 2 different things (and 2 different colors for the same thing).

**Comment by JosephTLyons** [comment]
This is a huge issue for me.  I'm constantly confused by the colors of the tags and branches not matching.  Is there an update on this?

**Comment by MarHoff** [comment]
This is pretty confusing, if the problem is too complex too rightfully color every branch (with regard to remote notably) at least please use a different a specific color scheme for "checked out local branch" that should never be used in the graph for something else than the currently checked out local branch.

**Comment by JosephTLyons** [comment]
I’m extremely confused as to why this hasn’t been looked into or fixed by now.  I’m dyslexic and can sometimes simply not use Merge because of this.  This has been open for a very long time, could this be taken care of?

**Comment by scp** [comment]
Any update on this? Seems like a relatively easy fix, no? Surprised this is still an issue.

**Comment by JosephTLyons** [comment]
It is possible it could be a more challenging fix, but at any rate, its old enough it should be fixed by now.  This is really important for those of us who have mental hurdles to get over and for those who rely on color coding of things to help get oner those hurdles.

**Comment by kpowick** [comment]
Can't believe this isn't fixed by now.  How hard can it be to colour the labels the same as the branches?

**Comment by rolandasb** [comment]
Let's not make assumptions that it's easy to fix without knowing anything about the codebase. I'm sure devs are prioritising issues and will address this eventually.

**Comment by kpowick** [comment]
Hi @rolandasb ,

This "problem" was noticed and reported almost 2 years ago and is a UX issue that I don't see in other GUI Git clients.

I understand that resources for any project are limited, and the popularity of SM means a lot of issues/requests end up in the tracker (500+ today).  However, I think that such a fundamental aspect of the product (the graph), deserves better attention.  Perhaps this issue has been lost in the sea of requests, which is why I commented in the first place.  More comments might garner more attention. 🚒

You are correct in your assumption 😎 that I do not have access to the codebase.  However, if one is coding to colour the branches and create the labels to position correctly with those branches, then it's not a stretch to assume that setting the label colour to match the branch isn't overly complex.

I could be wrong though.  Again, I'm just trying to draw attention to a long outstanding issue that has, IMO, significant UI/UX impact.

**Comment by scp** [comment]
Glad to see more regular updates being released now.
Every time I see "Update Available" I pray this issue has been addressed.

**Comment by JosephTLyons** [comment]
> Let's not make assumptions that it's easy to fix without knowing anything about the codebase. I'm sure devs are prioritizing issues and will address this eventually.

I'll agree with you that this could very well be a really difficult fix.  I will not minimize the effort it could possibly take to fix it, but I don't think that this is an issue that should be addressed "eventually."  This is actually an issue of accessibility for some people.  I'm dyslexic and heavily rely on color-coding to make tools more usable for me.  This has been around long enough that I really can't think of a good excuse as to why it hasn't been fixed.

**Comment by MarHoff** [comment]
> Let's not make assumptions that it's easy to fix without knowing anything about the codebase. I'm sure devs are prioritising issues and will address this eventually.

I could totally understand that, but considering the impact of this bug it would be nice to at least have an informed opinion of a maintainer about the issue. For all we know this might even have flung totally under their radar as the last staff action seems to be a tag 1 year and half ago.

And the impact might not be neutral for the product growth because while testing I initially feared that something was utterly broken before realizing that it was "just" a very annoying UX only bug.

**Comment by dpjohnst** [comment]
Thank you to everyone who has shared their feedback on this topic!

As of Sublime Merge Build 2033 (development build), we've updated the commit graph theming (branches will now match the graph edge they're attached to).

We'd love to hear your feedback on the updates. For general things, feel free to share it here.
 For more specific issues, you can create a new issue at https://github.com/sublimehq/sublime_merge/issues/new/choose.

Thanks,
\- Dylan

**Comment by JosephTLyons** [comment]
> Thank you to everyone who has shared their feedback on this topic!
> 
> 
> 
> As of Sublime Merge Build 2033 (development build), we've updated the commit graph theming (branches will now match the graph edge they're attached to).
> 
> 
> 
> We'd love to hear your feedback on the updates. For general things, feel free to share it here.
> 
>  For more specific issues, you can create a new issue at https://github.com/sublimehq/sublime_merge/issues/new/choose.
> 
> 
> 
> Thanks,
> 
> \- Dylan

How do we obtain the dev build?

**Comment by dpjohnst** [comment]
Hi @JosephTLyons,

See https://www.sublimemerge.com/dev

Kind regards,
\- Dylan

**Comment by scp** [comment]
@dpjohnst THANK YOU 🙌🏼 I'm so ridiculously happy about this. It has been so contextually jarring for me and was the only issue letting down this amazing tool. I knew this day would finally come 🎉

**Comment by JosephTLyons** [comment]
Just checked it out.  This is fantastic and helps so much.  This one feature was a huge contributing factor to me not entirely switching to Merge (even though I own it).  I think I can fully switch over to it now.  Excited for what may be next in the feature pipeline.

**Comment by dpjohnst** [comment]
Hi all,

The upgraded commit graph is now available in Sublime Merge Build 2038 (stable build).

Thanks,
\- Dylan
