### ISSUE TITLE
Command "Finish Hotfix" does not exists

### ISSUE THREAD

**Issue by nikoskip** [sublimehq/sublime_merge#261]
**Version info**

 - OS: MacOS 10.13.6
 - Build: 1084

**Description**

Missing "Finish Hotfix" command

**Steps to reproduce**

1. Open the command pallete
2. Search for "finish" or "Git flow"

**Expected behavior**

A "Git Flow: Finish Hotfix" command

**Screenshots**

![image](https://user-images.githubusercontent.com/1230033/49024557-884e4300-f178-11e8-8fe5-621c7b891807.png)

**Comment by jskinner** [comment]
Thanks for the report - this has been fixed in the current series of dev builds, at https://www.sublimemerge.com/dev. The next stable build with this fix shouldn't be too long away.

**Comment by twkm** [comment]
I'm still having the same issue in build 1099 on Mac OS 10.14.1.

**Comment by nikoskip** [comment]
Command still not available on build 1103. I really want to migrate from my current Git client, but without this feature I can't.

**Comment by jskinner** [comment]
Apologies, I misread the initial bug report, and conflated it in my head with a different issue with the Git Flow menu items.

I've pushed a fix for this locally, it'll be available in the next build.

**Comment by nikoskip** [comment]
Thank you @jskinner !

**Comment by jskinner** [comment]
Actually @nikoskip could I get you to send me the debug information for the repository in question (from the Help/Debug Information menu), either pasting it in here or emailing me at jps@sublimetext.com

**Comment by nikoskip** [comment]
Sure, I will send it to your e-mail. Thanks.

**Comment by jskinner** [comment]
Thanks for the Debug Information.

The underlying issue is that Sublime Merge isn't handling missing git flow prefix values correctly. You don't have a `gitflow.prefix.bugfix config` value defined, which triggers a bug in Sublime Merge that causes it to think all hotfix branches are actually bugfix branches, resulting in no Finish Hotfix entries in the Command Palette.

This will be fixed in the next build from our end, but as a work around until then you can use the `Tools/Configure Git Flow` menu item, and setup a prefix for bugfix branches (typically 'bugfix/')

**Comment by nikoskip** [comment]
Thanks for the work around !

**Comment by BenjaminSchaaf** [comment]
Should be fixed since build 1105
