### ISSUE TITLE
Clone repository cannot create valid folder

### ISSUE THREAD

**Issue by jasonycw** [sublimehq/sublime_merge#277]
**Version info**

 - OS: Windows 10
 - Build: 1091

**Description**

SM cannot clone repository with special character in the name

**Steps to reproduce**

1. Open SM
2. Git clone this `https://github.com/jasonycw/test-repo.git`
3. Cannot clone with the bellow error pop up<br> 
![image](https://user-images.githubusercontent.com/4518597/49276302-0d0ec900-f4b9-11e8-84bd-3dd91992672d.png)

**Expected behavior**

Can create the folder `test-repo` and clone normally

**Screenshots**
![image](https://user-images.githubusercontent.com/4518597/49276705-354af780-f4ba-11e8-8c6d-14bcf4edcfc0.png)

**Comment by Scrxtchy** [comment]
Also getting a problem where selecting a path does not add the slash. Results in a different error
![image](https://user-images.githubusercontent.com/12771982/49297181-458cc200-f50e-11e8-90e3-75b85fd9471a.png)

**Comment by dylanjohnston** [comment]
Thanks for the reports! 

This has been addressed in Dev Build 1093.

**Comment by jasonycw** [comment]
@dylanjohnston still the same issue with 1094
![image](https://user-images.githubusercontent.com/4518597/49421843-8d407180-f7cc-11e8-809f-c11360f83fc8.png)

**Comment by jasonycw** [comment]
Tested on Dev Build 1096, and the result is good for my case.

Not sure for @Scrxtchy one though.
