### ISSUE TITLE
Cloning repository fails with syntax error.

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#286]
**Version info**

 - OS: Windows 10 x64
 - Build: 1093

**Description**

Just tried to clone a repository from github without luck. The screenshot below shows the error message.

It says the process (git) failed due to syntax errors in the file/path syntax. Maybe the backslashes are not escaped correctly when passed to git?

Running `git clone` from command line works well.

**Steps to reproduce**

1. Open SM
2. Run command Menu > File > Clone Repository
3. ...

**Expected behavior**

Cloning should work

**Screenshots**

SM fails.
![grafik](https://user-images.githubusercontent.com/16542113/49333566-52b6b900-f5c1-11e8-8dc4-5022e7385e5d.png)

CMD works.
![grafik](https://user-images.githubusercontent.com/16542113/49333605-f7d19180-f5c1-11e8-99ca-ac95e23bc630.png)

**Comment by dylanjohnston** [comment]
Thanks for the report! 

This has been addressed in Dev Build 1093.

**Comment by deathaxe** [comment]
Unfortunately the issue persists. Even tried to set _Destination Path_ to something without spaces without luck. Tried different repo as well. 

I use portable SM, but have my installed `git version 2.19.0.windows.1` client in use. The bundled one is removed.

If I can provide any further info, let me know.

**Comment by dylanjohnston** [comment]
Thanks for the information. Could you confirm if the issue exists in Dev Build 1095?

Thanks,
- Dylan

**Comment by deathaxe** [comment]
Just tried 1096. Works now.
