### ISSUE TITLE
Preferences window is too big

### ISSUE THREAD

**Issue by AmjadHD** [sublimehq/sublime_merge#684]
**Version info**

 - OS: Windows 10
 - Build: 2000

**Description**

Preferences window is too big that i can't close it with with the <kbd>x</kbd> button
![image](https://user-images.githubusercontent.com/33235928/75979919-cc82d400-5ee1-11ea-8297-11e2e1e00510.png)
but when i resize it, it is fixed:
![alt](https://user-images.githubusercontent.com/33235928/75980090-1f5c8b80-5ee2-11ea-830e-833ede17505f.gif)

**Comment by dpjohnst** [comment]
Hi @AmjadHD,

Thank you for reporting this!
We will be investigating ways we can solve this issue - I'll keep you updated.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @AmjadHD,

This should be fixed in the latest development build of Sublime Merge. Could you confirm this for me on your end?

Many thanks,
\- Dylan

**Comment by AmjadHD** [comment]
Still isn't properly fixed (half the title bar is still off screen):
![image](https://user-images.githubusercontent.com/33235928/77909334-78bf9c80-728d-11ea-9b81-2da46a4bc75a.png)
