### ISSUE TITLE
Diff view behaves incorrectly when using working-tree-encoding

### ISSUE THREAD

**Issue by Phaiax** [sublimehq/sublime_merge#705]
**Version info**

 - OS: Windows 10
 - Build: Dev Channel 2004

**Description**

When setting [working-tree-encoding](https://git-scm.com/docs/gitattributes) to an non utf-8 encoding, the diff view starts showing changes in parts of the file that have been untouched.
When staging hunks, the index shows changes where I do not really understand what is going on.

See also https://forum.sublimetext.com/t/working-tree-encoding-and-git-diff/5036

**Steps to reproduce**
```
rm -rf testrepo
git init testrepo
cd testrepo
echo "*.c    text working-tree-encoding=windows-1252" > .gitattributes
git add .gitattributes
git commit -am"Add encoding setting"
printf "A\nnormal\nC\nFile" > normal.c
printf "A\nC\nFile\nwith\nUmlauts\nin\nwindows1252\nencoding\n\nFirst: \xc4\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\nSecond:\xfc\n.\n.\n" > umlaut.c
# cat umlaut.c | iconv -f windows-1252 -t utf-8
git add *.c
git commit -m"some C files"
# now only change the first Umlaut:
# cat umlaut.c | sed 's/\xc4/\xc6/g' | iconv -f windows-1252 -t utf-8
sed -i 's/\xc4/\xc6/g' umlaut.c
echo "Changed one umlaut in umlaut.c. View in git diff:"
git diff
echo "View in sublime merge. Any key to continue"
read
echo "Now alternatively commit the whole file or only chunks in sublime merge or git and see what happens."

echo "Staging the first hunk in sublime merge makes it still appear both in git diff and git diff --staged"
echo "Staging the second hunk in sublime merge makes the second hunk appear both in git diff and git diff --staged"
echo "Staging the whole file in sublime merge makes only the first hunk appear in git diff --staged and the sublime merge staged area, as expected."
```

**Expected behavior**

Staging via Sublime Merge behaves like `git add` or `git add -i`

**Comment by BenjaminSchaaf** [comment]
We've got a fix for this in the pipeline

**Comment by BenjaminSchaaf** [comment]
This should be fixed in build 2005

**Comment by Phaiax** [comment]
Hi

Tested with 2005.
The umlauts like ü are not marked as changed anymore, but there is still a problem with " and '.

The diff view marks all occurences of `“` and `’` as changed if at least one byte in the file is changed. I looked via xxd, and the marked bytes in the file are 0x92/0x93.
```
00000000: 444f 5542 4c45 5155 4f54 9353 494e 474c  DOUBLEQUOT.SINGL
00000010: 4551 554f 5492 454e 442f 2a2a 2a2a 2a2a  EQUOT.END/******
```
for this file
```
DOUBLEQUOT“SINGLEQUOT’END/**
```

The right part of the diff shows
```
DOUBLEQUOTÀœSINGLEQUOTÀ™END/**
```

((Maybe this affects the boldly bordered part of [that table](https://en.wikipedia.org/wiki/Windows-1252) where the unicode equivalent is two bytes?))

And, if I add new Umlauts, all occourences of Umlauts in that line are printed wrong on the right part of the diff:
`ü -> Ã¼, ä -> Ã¤`

**Comment by BenjaminSchaaf** [comment]
Thanks for catching that, we've got a fix in the pipeline

**Comment by BenjaminSchaaf** [comment]
This should be fixed in build 2006

**Comment by Phaiax** [comment]
confirm as fixed in build 2006
