### ISSUE TITLE
Directory junctions are marked as Untracked (even if ignored)

### ISSUE THREAD

**Issue by 1nv** [sublimehq/sublime_merge#830]
**Version info**

 - OS: Windows 10 Pro 1903
 - Build: 2025

**Description**

Starting from build 2025, directory junctions started being marked as Untracked, even if explicitly ignored via .gitignore.

**Steps to reproduce**

1. Create a new repository.
2. Add directory '**dir**' to its root.
3. Create a directory junction under root, named '**link**', pointing to '**dir**'.
4. Create '**.gitignore**' with contents:
```
link/
dir/
```
5. Commit '**.gitignore**'.
6. Open the repository with Sublime Merge.

**Expected behavior**

Sublime Merge shows '**No changes**'.

**Actual behavior**

Sublime Merge shows '**1 unstaged file**'.

**Screenshots**
![sm_bug](https://user-images.githubusercontent.com/10288828/88165854-06e5d700-cc1f-11ea-837e-f5254b325280.png)

**Comment by dpjohnst** [comment]
Hi @1nv,

Thanks for reporting this issue - we'll be investigating this further.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @1nv,

This has been fixed in development build 2026, and will be available in the stable channel soon.

Kind regards,
\- Dylan

**Comment by 1nv** [comment]
Hi Dylan,

I have installed 2026 but, unfortunately, the issue still persists.

Kind Regards,
Eugene

**Comment by dpjohnst** [comment]
Hi @1nv,

Thanks for reporting this - I'm investigating this further. Stay tuned.

**Comment by dpjohnst** [comment]
Hi @1nv,

Thanks again for reporting this.

We've investigated further, and identified the cause of the issue.
A fix will be available in the next build.

Kind regards,
\- Dylan

**Comment by 1nv** [comment]
Hi @dpjohnst,

The issue appears to be fixed in 2028.
Thank you!

Kind Regards,
Eugene

**Comment by jimon** [comment]
2028 build, still not solved for me:
![image](https://user-images.githubusercontent.com/1333661/89630179-46f3bd80-d89f-11ea-8784-40a49f4baa79.png)
