### ISSUE TITLE
SM shows loading animation in diff hunks and consumes 100% of one core with certain commit.

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#917]
**Version info**

 - OS: Windows 10 x64 2004
 - Build: 2033

**Description**

Looks like SM runs into a infinite loop while trying to display diffs of js/jsx files. It shows the loading animation and consumes a lot of CPU. Closing the window doesn't close the app. Need to kill it via Task Manager.

**Steps to reproduce**

1. Clone https://github.com/sublimehq/Packages
2. Select commit 558e49baf6f85fe041c99545344a40d7d604122d [JavaScript] Meta Numbers (#2463)
3. Scroll down to the diff hunks

**Expected behavior**

Diffs should show.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/16542113/93384486-2edf6880-f865-11ea-8450-21ce7cf186ab.png)

**Comment by spezzino** [comment]
Same issue happening on Mac

- OS: Mac OS Catalina 10.15.6 (19G2021)
- Build: 2032



![image](https://user-images.githubusercontent.com/2013367/94255869-077f4e80-ff7d-11ea-9cbd-83f120d7e21d.png)

**Comment by deathaxe** [comment]
Seems to be fixed in 2034.

**Comment by dpjohnst** [comment]
Hi all,

Just following up - this was fixed in build 2034. It will additionally be fixed in the next stable build.

Kind regards,
\- Dylan

**Comment by spezzino** [comment]
Issue still presist on build 2034 for Mac

![image](https://user-images.githubusercontent.com/2013367/94780928-a694c200-0425-11eb-849c-3aae21124158.png)

**Comment by dpjohnst** [comment]
Hi @spezzino,

Thank you for the additional information.

Is it a specific commit which causes infinite loading? If so, what file types are contained in the commit?

Thanks,
\- Dylan

**Comment by spezzino** [comment]
Hi @dpjohnst 
Was happening with all commits, the one in the picture, had images in (maybe that triggered the issue).

I have deleted and reinstalled this build again, and is working fine for now.

**Comment by dpjohnst** [comment]
Hi @spezzino,

If you don't mind, could you open a separate issue on the issue tracker for this issue (it seems like a slightly different issue).
https://github.com/sublimehq/sublime_merge/issues/new/choose

From there, we can definitely investigate further to resolve the issue.
It would be great if you could include:
Platform
Sublime Merge version
The file types in the commit for which you first notice this issue occuring

Thanks,
\- Dylan

**Comment by dpjohnst** [comment]
Hi all,

The original issue should be resolved in Sublime Merge 2038 (stable).

Thanks for your help,
\- Dylan
